### ISSUE TITLE
FactionList class isn't needed

### ISSUE THREAD

**Issue by lgibson02** [LegendOfMCPE/PocketFactions#1]
Couldn't we just put everything in FactionList class to the Faction class and just make them static?

**Comment by PEMapModder** [comment]
FactionList was created because it is easier to work with multiple factions. For example, the faction who owned a particular chunk. But if you don't like it, change it. It's OK. Just I don't have time to do this.

**Comment by iJoshuaHD** [comment]
i think this issue is ok now.

**Comment by PEMapModder** [comment]
I wanted to label it as "wontfix" but well... lol

**Comment by PEMapModder** [comment]
The `Db-Rewrite` branch proved the great use of this class xD

**Comment by iJoshuaHD** [comment]
just merge the rewrite already. no one will oppose on it...
