### ISSUE TITLE
 [CRITICAL] Could not load plugin'PocketFactions': Unknown dependency

### ISSUE THREAD

**Issue by cre2016** [LegendOfMCPE/PocketFactions#15]
#812
[CRITICAL] Could not load plugin 'PocketFactions': Unknown dependency
12:41:39 [CRITICAL] Could not load plugin 'PocketFactions': circular dependency detected

maybe caused by: xEcon can't work
Error: Call to a member function close() on null
File: /xEcon-master1102/src/xecon/XEcon
Line: 100
Type: E_ERROR

[NOTICE] ArrayOutOfBoundsException: "Undefined index: path" (E_NOTICE) in "/xEcon-master1102/src/xecon/provider/JSONDataProvider" at line 21

**Comment by PEMapModder** [comment]
The required dependencies (xEcon and StatsCore) are missing.
