### ISSUE TITLE
Chunk::fromObject() 

### ISSUE THREAD

**Issue by cre2016** [LegendOfMCPE/PocketFactions#17]
pm#878  latest PocketFactions in github

16:04:03 [NOTICE] InvalidArgumentException: "Argument 1 passed to pocketfactions\faction\Chunk::fromObject() must be an instance of pocketmine\level\Position, array given, called in E:\pe\fu wu qi\PocketMine-MP-Alpha_1.4dev-822\plugins\PocketFactions-master1110\src\pocketfactions\faction\Faction.php on line 95 and defined" (E_RECOVERABLE_ERROR) in "/PocketFactions-master1110/src/pocketfactions/faction/Chunk" at line 57
16:04:03 [DEBUG] #0 /src/pocketmine/Server(1654): pocketmine\Server->enablePlugins(integer 1)
16:04:03 [DEBUG] #1 /src/pocketmine/PocketMine(440): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://E:/pe/fu wu qi/PocketMine-MP-Alpha_1.4dev-822/PocketMine-MP.phar/, string E:\pe\fu wu qi\PocketMine-MP-Alpha_1.4dev-822\, string E:\pe\fu wu qi\PocketMine-MP-Alpha_1.4dev-822\plugins)
16:04:03 [DEBUG] #2 (1): require(string phar://E:/pe/fu wu qi/PocketMine-MP-Alpha_1.4dev-822/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
16:04:03 [INFO] Disabling PocketFactions v1.0.0

**Comment by PEMapModder** [comment]
The plugin is not ready for even testing yet.

P.S. are you Chinese? I recognized "fu wu qi" from your path.

**Comment by cre2016** [comment]
Right .

**Comment by cre2016** [comment]
can you fix it now ,I can't open my server with this plugin .

**Comment by PEMapModder** [comment]
Even if I fix this bug there are still tons of bugs to fix.

**Comment by cre2016** [comment]
I see .

**Comment by PEMapModder** [comment]
BTW, @llj070 you can help us test xEcon.

**Comment by cre2016** [comment]
ok ,I will test it .

**Comment by cre2016** [comment]
ok.I will test it .
2014-12-13 PM10:01于 "PEMapModder" notifications@github.com写道：
