### ISSUE TITLE
get() on line 520

### ISSUE THREAD

**Issue by cre2016** [LegendOfMCPE/PocketFactions#18]
Fatal error: Call to a member function get() on null in E:\pe\fu wu qi\PocketMine-MP-Alpha_1.4dev-822\plugins\PocketFactions-master1110\src\pocketfactions\Main.php on line 520

**Comment by PEMapModder** [comment]
Please stop reporting bugs on PocketFactions. It isn't even ready to be tested.

**Comment by cre2016** [comment]
ok
