### ISSUE TITLE
Thorough rewrite

### ISSUE THREAD

**Issue by PEMapModder** [LegendOfMCPE/PocketFactions#20]
After a few months I found that the current codebase is not very efficient for the long term. Members of LegendOfMCPE team, please vote whether you agree this plugin to be rewritten.

**Comment by PEMapModder** [comment]
My stance is to rewrite. There are many messy or unreadable code on the current master branch. For example, the methods to create s new Faction instance could have a lot of undefined behavior. We'll have a hard time testing this plugin of we don't rewrite.

**Comment by iJoshuaHD** [comment]
i vote rewrite because tbh, i am lost which and what doesnt work :P

**Comment by iksaku** [comment]
I vote **YES**, the same reasons of @ijoshuahd xD and that I don't fully understand the code :S

**Comment by PEMapModder** [comment]
Apart from giving these reasons, please also make sure we can avoid them after a rewrite. We don't want to keep rewriting and making the same mistakes :joy:

**Comment by iksaku** [comment]
Sup :3 but... what type of API will it take? Method oriented or Object oriented?

**Comment by PEMapModder** [comment]
How can we possibly make it method-oriented?

**Comment by iksaku** [comment]
Like EssentialsPE ;)

**Comment by PEMapModder** [comment]
Object-oriented. It is just unreasonable to make extra APIs while, if we make it like the old one, we already have the API methods at the Faction class. For example, we can have a getFaction() method and the Faction class will have most API methods you need, so it should be object-oriented in this case.

**Comment by iksaku** [comment]
I don't know the difference xD I just call them "API" xD

**Comment by PEMapModder** [comment]
You asked it yourself :grin:

**Comment by iJoshuaHD** [comment]
reading commits doesnt make sense if its a lot for me xD go rewrite!

**Comment by PEMapModder** [comment]
take a look at the `new` branch to see if you can withstand it.

**Comment by iJoshuaHD** [comment]
no D: xD

**Comment by PEMapModder** [comment]
Then try to xD

**Comment by iJoshuaHD** [comment]
noo!! :( xD it burns my eyes due to its complexity xD since im almost done with iMCPE Stuff, i can now catch up with the rewrite :D

**Comment by iJoshuaHD** [comment]
this time, i suggest is to implement things one by one then debug? implement its dependencies later then when its quite ready, implement its dependencies so the development would be more faster _imo_.

**Comment by iJoshuaHD** [comment]
in my observation, if we connect both projects like a pathway and each of these project arent even done or still WIP, making a move would be difficult.

**Comment by PEMapModder** [comment]
OK, so maybe we should finish xEcon and StatsCore first?

**Comment by PEMapModder** [comment]
but there are some things that cannot be tested one by one because they are interdependent. For example, you can't test factions without database, but you can't test database without some other things. As a result, it would come out strangely.

**Comment by PEMapModder** [comment]
When I look at [the oldest commit of MassiveCraft factions](https://github.com/MassiveCraft/Factions/tree/b3ac8f8614383b20e99105b38c0aa7bfff84b453/src/com/bukkit/mcteam/factions), they already had such much code.

**Comment by iJoshuaHD** [comment]
why dont you make a database creator class then? im not boasting but it really helps a lot. it creates a database for you if it doesnt exist. if only you saw MiniFactions plugin in the private git :P

**Comment by iJoshuaHD** [comment]
as for MassiveFactions i dont know about their history. i theorize that they already have that plugin WIP before they open sourced it.

**Comment by PEMapModder** [comment]
@iJoshuaHD if you copy your DBCreator class's createDB() function into the main class? It is just a function.

**Comment by iJoshuaHD** [comment]
yes but it creates a database for you if its new or the db is not found.

**Comment by PEMapModder** [comment]
Yes, so it is same as copying it into the onEnable() function xD

**Comment by iJoshuaHD** [comment]
i mean, my reply is all about ur post:

"but there are some things that cannot be tested one by one because they are interdependent. For example, you can't test factions without database, but you can't test database without some other things. As a result, it would come out strangely."

:P

**Comment by PEMapModder** [comment]
Default branch has been set to `new`. The `master` branch will be deleted one week later, and the `new` branch will be renamed to `master` two weeks later with a copy `new` branch remaining. Three weeks later the `new` branch will be deleted.

**Comment by caingaroo** [comment]
Theres a problem with the plugin it say somethi gs roung in FactionRanks

**Comment by PEMapModder** [comment]
@caingaroo plugin is not finished.
