### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Matthww** [LegendOfMCPE/PocketFactions#23]
Hello

I wanted to try your plugin so i maded a new test server and compiled your files in to a phar but i get this error:

[NOTICE] ArrayOutOfBoundsException: "Undefined index: permissions" (E_NOTICE) in "/PocketFactions/src/pocketfactions/faction/FactionRank" at line 32

I don't know if you already knows this

**Comment by iJoshuaHD** [comment]
this plugin is still in development. not quite fitted for an early test right now.
