### ISSUE TITLE
No permissions?!

### ISSUE THREAD

**Issue by dmo-ooo** [LegendOfMCPE/PocketFactions#26]
When I use this plugin I always get an error, this is the error:

[Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined index: permissions" (E_NOTICE) in "/PocketFactions/src/pocketfactions/faction/FactionRank" at line 32

**Comment by dmo-ooo** [comment]
Or is this plugin dead? This is the best factions plugin though!

**Comment by PEMapModder** [comment]
This plugin is not available for use, and will not be completed in a short time (or forever).
