### ISSUE TITLE
can't create a phar

### ISSUE THREAD

**Issue by Tolo0** [LegendOfMCPE/PocketFactions#29]
Hi. How do I use this plugin? Theys no yml file so can't use devtools on it.

**Comment by PEMapModder** [comment]
This plugin cannot be compiled by DevTools. It can be compiled by the make.php in the repo. You can also find a build in the bin directory, although it may not be updated every time.
However, this plugin is not ready to be used yet. When it is, we will submit it onto PocketMine Forums.

**Comment by Tolo0** [comment]
Hope to see this plugin active soon. I'm using faction pro atm. But it doesn't support multi world support. So I'll wait for this one. Thanks for replying 😉
