### ISSUE TITLE
Bad onDisable() support

### ISSUE THREAD

**Issue by PEMapModder** [LegendOfMCPE/PocketFactions#3]
This plugin seems to have a bad reloading support.

**Comment by PEMapModder** [comment]
But I labelled it as `wontfix` anyways. Anyone who wants to fix this issue can assign himself.

**Comment by iJoshuaHD** [comment]
why is that?

when i do /reload
the plugin is experiencing something strange?

**Comment by PEMapModder** [comment]
It doesn't occur yet, but we need to do some threading-related things with that. The server may be full of players when the plugin is loaded, and we must add support like AsyncTask on initialization

**Comment by PEMapModder** [comment]
Oops wrong commit name in 56832a4

**Comment by PEMapModder** [comment]
This issue only serves as a reminder.
