### ISSUE TITLE
Bad thread references

### ISSUE THREAD

**Issue by PEMapModder** [LegendOfMCPE/PocketFactions#6]
Objects and arrays must be serialized to pass to an async task. Right now, we have three choices for writing. The first one is to move the database format to the main thread and outwrite to harddisk in an AsyncTask such that only the I/O part is done, and the second one is to change it such that we only I/O the database on enable and disable, which would not lag the server so much, and then run it on the main thread. The third one is to convert the factions into arrays and then serialize such that they can be unserialized and then proceed the format at the new thread such that the formatting-into-binaries part is done at the new thread. However, the serialize-and-unserialize part takes a lot of time according to Mr. Hatman (NullFull: Don't you dare call his name!), so it is not a good method.

As for reading, the only method is to create instance on the main thread. So the current best solution for both in and out I can think of is to format/parse in the main thread and I/O at another thread. As we know, pthreads has some issues with objects, so we can create the instances in the thread and output them at onComplete($server) (this is new, a few minutes/less than one hour before).

**Comment by PEMapModder** [comment]
Please post your comment on this issue here. I am not sure what to do.

**Comment by iJoshuaHD** [comment]
why writing things does matter? if they want pocketfactions not to lag, why not limit their player slots?

**Comment by PEMapModder** [comment]
Because we save all the data in one file. The whole file will be rewritten if we output the database, so having 0 player = having 100 players. (I'll fix it such that it won't save if nothing in the database is changed, but 1 player still = 100 players) Moreover, this is the issue of disk writing speed, and even large servers with good hosts can lag with this. This is an issue of "blocking main thread", and the plugin reviewers won't accept the answer "their own fault to have many factions created".

**Comment by PEMapModder** [comment]
I consider this issue is "fixed", but it is a bad fix. You are welcome to reopen this issue or improve the code in this fix.
